# Generated by Django 6.0.7 on 2026-08-12 03:19

import src.commerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, upload_to=src.commerce.models.brand_logo_upload_path, validators=[src.commerce.models.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=src.commerce.models.product_image_upload_path, validators=[src.commerce.models.validate_image_upload]),
        ),
    ]
