ROBOTS = {
    "littlebot": {
        "name": "LIRO / Little Bot",
        "slug": "littlebot",
        "segment": "Robótica Educacional",
        "description": "Robô educacional inteligente para escolas, famílias, clínicas, creches e espaços de atendimento especializado.",
        "applications": ["escolas", "famílias", "clínicas", "creches", "espaços de atendimento especializado"],
        "image": "institutional/imgs/service/little-bot-sobre-a-mesa.webp",
        "image_width": 345,
        "image_height": 410,
        "image_alt": "LIRO / Little Bot em aplicação de robótica educacional",
        "card_image": "institutional/imgs/icon/services-7-01.png",
    },
    "orbit": {
        "name": "Orbit Bot / Patrol Bot",
        "slug": "orbit",
        "segment": "Segurança Inteligente",
        "description": "Robô de patrulhamento e segurança para grandes áreas, com navegação autônoma, visão inteligente e monitoramento em tempo real.",
        "applications": ["patrulhamento", "segurança para grandes áreas", "monitoramento em tempo real"],
        "image": "institutional/imgs/service/orbit-fazendoŕonda.webp",
        "image_width": 790,
        "image_height": 443,
        "image_alt": "Orbit Bot em patrulhamento e segurança",
        "card_image": "institutional/imgs/icon/services-7-02.png",
    },
    "neo-bot": {
        "name": "Neo Bot",
        "slug": "neo-bot",
        "segment": "Recepção e Atendimento",
        "description": "Robô de recepção e atendimento com diálogo multilíngue, IA, reconhecimento facial e apresentação de produtos.",
        "applications": ["recepção", "atendimento", "apresentação de produtos"],
        "image": "institutional/imgs/bg-img/neo-bot-em-acao.webp",
        "image_width": 410,
        "image_height": 371,
        "image_alt": "Neo Bot em operação",
        "card_image": "institutional/imgs/icon/services-7-03.png",
    },
    "waiter-bot": {
        "name": "Waiter Bot",
        "slug": "waiter-bot",
        "segment": "Entrega e Apoio Operacional",
        "description": "Robô de entrega e apoio operacional para restaurantes, hotéis, supermercados e ambientes de atendimento.",
        "applications": ["restaurantes", "hotéis", "supermercados", "ambientes de atendimento"],
        "image": "institutional/imgs/icon/services-7-04.png",
        "image_width": 37,
        "image_height": 34,
        "image_alt": "Waiter Bot",
        "card_image": "institutional/imgs/icon/services-7-04.png",
        "needs_content": "Não há imagem real específica do Waiter Bot no projeto; foi preservado o ícone existente do card.",
    },
    "hygibot-dune-bot": {
        "name": "HygiBot / Dune Bot",
        "slug": "hygibot-dune-bot",
        "segment": "Limpeza Autônoma",
        "description": "Robô autônomo que lava, varre, aspira e passa pano em shoppings, indústrias, hospitais e grandes áreas.",
        "applications": ["shoppings", "indústrias", "hospitais", "grandes áreas"],
        "image": "institutional/imgs/bg-img/duno-bot-em-limpeza-mercado.webp",
        "image_width": 410,
        "image_height": 371,
        "image_alt": "HygiBot / Dune Bot em limpeza autônoma",
        "card_image": "institutional/imgs/icon/services-7-05.png",
    },
    "buddy-bot": {
        "name": "Buddy Bot",
        "slug": "buddy-bot",
        "segment": "Inspeção e Segurança Patrimonial",
        "description": "Robô quadrúpede para inspeção, segurança patrimonial, engenharia, obras e áreas de difícil acesso.",
        "applications": ["inspeção", "segurança patrimonial", "engenharia", "obras", "áreas de difícil acesso"],
        "image": "institutional/imgs/service/budy-bot-rosto.webp",
        "image_width": 455,
        "image_height": 270,
        "image_alt": "Buddy Bot para inspeção e segurança patrimonial",
        "card_image": "institutional/imgs/icon/services-7-06.png",
    },
    "carebot": {
        "name": "CareBot",
        "slug": "carebot",
        "segment": "Saúde e Monitoramento",
        "description": "Robô assistivo para residências, clínicas, hospitais, farmácias e monitoramento inteligente de indicadores de saúde.",
        "applications": ["residências", "clínicas", "hospitais", "farmácias", "monitoramento inteligente de indicadores de saúde"],
        "image": "institutional/imgs/about/med-bot-detalhes.webp",
        "image_width": 210,
        "image_height": 220,
        "image_alt": "CareBot em aplicação assistiva de saúde",
        "card_image": "institutional/imgs/icon/services-7-01.png",
    },
    "hostbot": {
        "name": "HostBot",
        "slug": "hostbot",
        "segment": "Recepção, Eventos e Atendimento",
        "description": "Robô host com duas telas e inteligência artificial para recepção, eventos, empresas, museus, galerias e bancos.",
        "applications": ["recepção", "eventos", "empresas", "museus", "galerias", "bancos"],
        "image": "institutional/imgs/service/connect-bot-recpcionando-pessoas.webp",
        "image_width": 1320,
        "image_height": 740,
        "image_alt": "HostBot em recepção e atendimento",
        "card_image": "institutional/imgs/icon/services-7-02.png",
    },
    "mowerbot": {
        "name": "MowerBot",
        "slug": "mowerbot",
        "segment": "Operação em Áreas Externas",
        "description": "Robô cortador de grama por controle remoto para terrenos irregulares, taludes, praças e grandes áreas externas.",
        "applications": ["terrenos irregulares", "taludes", "praças", "grandes áreas externas"],
        "image": "institutional/imgs/icon/services-7-03.png",
        "image_width": 35,
        "image_height": 34,
        "image_alt": "MowerBot",
        "card_image": "institutional/imgs/icon/services-7-03.png",
        "needs_content": "Não há imagem real específica do MowerBot no projeto; foi preservado o ícone existente do card.",
    },
}

ROBOT_LIST = tuple(ROBOTS.values())


def robot_title(robot):
    return f"{robot['name']} | Xyron Robotics | Smart Control Brasil"


def robot_canonical_path(robot):
    return f"/robos/{robot['slug']}/"
