XYRON_ROBOT_PAGES = (
    {
        "key": 'littlebot',
        "name": 'LIRO / Little Bot',
        "slug": 'littlebot',
        "view": 'xyron_littlebot',
        "template": 'institutional/pages/xyron/littlebot/littlebot.html',
        "title": 'LIRO / Little Bot | Robô Educacional Interativo | Smart Control Brasil',
        "description": 'Conheça o LIRO / Little Bot, robô interativo para educação, experiências STEM, demonstrações e ambientes de aprendizagem e tecnologia.',
        "image": 'institutional/imgs/service/little-bot-sobre-a-mesa.webp',
        "width": 345,
        "height": 410,
        "alt": 'LIRO / Little Bot em aplicação de robótica educacional',
    },
    {
        "key": 'orbit',
        "name": 'Orbit Bot / Patrol Bot',
        "slug": 'orbit',
        "view": 'xyron_orbit',
        "template": 'institutional/pages/xyron/orbit/orbit.html',
        "title": 'Orbit Bot | Robô de Patrulhamento e Segurança | Smart Control Brasil',
        "description": 'Robô de patrulhamento e segurança para grandes áreas, com navegação autônoma, visão inteligente e monitoramento em tempo real.',
        "image": 'institutional/imgs/service/orbit-fazendo-ronda.webp',
        "width": 790,
        "height": 443,
        "alt": 'Robô Orbit em patrulhamento de segurança',
    },
    {
        "key": 'neo_bot',
        "name": 'Neo Bot',
        "slug": 'neo-bot',
        "view": 'xyron_neo_bot',
        "template": 'institutional/pages/xyron/neo-bot/neo-bot.html',
        "title": 'Neo Bot | Robô de Recepção e Atendimento | Smart Control Brasil',
        "description": 'Robô de recepção e atendimento com diálogo multilíngue, IA e apoio à apresentação de produtos em experiências corporativas.',
        "image": 'institutional/imgs/bg-img/neo-bot-em-acao.webp',
        "width": 410,
        "height": 371,
        "alt": 'Robô Neo Bot em operação',
    },
    {
        "key": 'waiter_bot',
        "name": 'Waiter Bot',
        "slug": 'waiter-bot',
        "view": 'xyron_waiter_bot',
        "template": 'institutional/pages/xyron/waiter-bot/waiter-bot.html',
        "title": 'Waiter Bot | Robô de Entrega e Apoio Operacional | Smart Control Brasil',
        "description": 'Robô de entrega e apoio operacional para restaurantes, hotéis, supermercados e ambientes de atendimento.',
        "image": 'institutional/imgs/icon/services-7-04.png',
        "width": 37,
        "height": 34,
        "alt": 'Ícone do Waiter Bot',
    },
    {
        "key": 'hygibot_dune_bot',
        "name": 'HygiBot / Dune Bot',
        "slug": 'hygibot-dune-bot',
        "view": 'xyron_hygibot_dune_bot',
        "template": 'institutional/pages/xyron/hygibot-dune-bot/hygibot-dune-bot.html',
        "title": 'HygiBot / Dune Bot | Robô de Limpeza Autônoma | Smart Control Brasil',
        "description": 'Robô autônomo que lava, varre, aspira e passa pano em shoppings, indústrias, hospitais e grandes áreas.',
        "image": 'institutional/imgs/bg-img/duno-bot-em-limpeza-mercado.webp',
        "width": 410,
        "height": 371,
        "alt": 'Robô Dune Bot em limpeza autônoma',
    },
    {
        "key": 'buddy_bot',
        "name": 'Buddy Bot',
        "slug": 'buddy-bot',
        "view": 'xyron_buddy_bot',
        "template": 'institutional/pages/xyron/buddy-bot/buddy-bot.html',
        "title": 'Buddy Bot | Robô Quadrúpede para Inspeção e Segurança | Smart Control Brasil',
        "description": 'Robô quadrúpede para inspeção, segurança patrimonial, engenharia, obras e áreas de difícil acesso.',
        "image": 'institutional/imgs/service/budy-bot-rosto.webp',
        "width": 455,
        "height": 270,
        "alt": 'Buddy Bot para inspeção e segurança patrimonial',
    },
    {
        "key": 'carebot',
        "name": 'CareBot',
        "slug": 'carebot',
        "view": 'xyron_carebot',
        "template": 'institutional/pages/xyron/carebot/carebot.html',
        "title": 'CareBot | Robô Assistivo para Saúde e Atendimento | Smart Control Brasil',
        "description": 'CareBot é uma solução robótica assistiva para residências, clínicas, hospitais, farmácias e ambientes de saúde e atendimento.',
        "image": 'institutional/imgs/about/med-bot-detalhes.webp',
        "width": 210,
        "height": 220,
        "alt": 'CareBot em aplicação assistiva de saúde',
    },
    {
        "key": 'hostbot',
        "name": 'HostBot',
        "slug": 'hostbot',
        "view": 'xyron_hostbot',
        "template": 'institutional/pages/xyron/hostbot/hostbot.html',
        "title": 'HostBot | Robô Host para Recepção e Eventos | Smart Control Brasil',
        "description": 'Robô host com duas telas e inteligência artificial para recepção, eventos, empresas, museus, galerias e bancos.',
        "image": 'institutional/imgs/service/connect-bot-recpcionando-pessoas.webp',
        "width": 1320,
        "height": 740,
        "alt": 'HostBot em recepção e atendimento',
    },
    {
        "key": 'mowerbot',
        "name": 'MowerBot',
        "slug": 'mowerbot',
        "view": 'xyron_mowerbot',
        "template": 'institutional/pages/xyron/mowerbot/mowerbot.html',
        "title": 'MowerBot | Robô Cortador de Grama para Áreas Externas | Smart Control Brasil',
        "description": 'Robô cortador de grama por controle remoto para terrenos irregulares, taludes, praças e grandes áreas externas.',
        "image": 'institutional/imgs/icon/services-7-03.png',
        "width": 35,
        "height": 34,
        "alt": 'Ícone do MowerBot',
    },
)

XYRON_ROBOT_PAGE_BY_KEY = {robot["key"]: robot for robot in XYRON_ROBOT_PAGES}
