# Generated by Django 6.0.7 on 2026-08-12 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salespeople', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('COMPANY', 'Empresa'), ('INDIVIDUAL', 'Pessoa física'), ('PUBLIC_ORGANIZATION', 'Órgão público'), ('SCHOOL', 'Escola'), ('CONDOMINIUM', 'Condomínio'), ('OTHER', 'Outro')], default='COMPANY', max_length=30)),
                ('legal_name', models.CharField(max_length=180)),
                ('trade_name', models.CharField(blank=True, max_length=180)),
                ('document', models.CharField(blank=True, max_length=20, null=True)),
                ('state_registration', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=12)),
                ('address_line', models.CharField(blank=True, max_length=180)),
                ('address_number', models.CharField(blank=True, max_length=30)),
                ('address_extra', models.CharField(blank=True, max_length=120)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo'), ('PROSPECT', 'Prospect')], default='PROSPECT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='salespeople.salesperson')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['legal_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('document__isnull', False), models.Q(('document', ''), _negated=True)), fields=('document',), name='unique_customer_document_when_present')],
            },
        ),
    ]
