# Generated by Django 6.0.7 on 2026-08-13 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_customer_relationships(apps, schema_editor):
    BusinessUnit = apps.get_model("backoffice", "BusinessUnit")
    Customer = apps.get_model("customers", "Customer")
    CustomerBusinessRelationship = apps.get_model("customers", "CustomerBusinessRelationship")
    business_unit, _ = BusinessUnit.objects.get_or_create(
        code="SMART_CONTROL",
        defaults={
            "name": "Smart Control Brasil",
            "slug": "smart-control",
            "is_active": True,
        },
    )
    for customer in Customer.objects.all().iterator():
        CustomerBusinessRelationship.objects.get_or_create(
            customer_id=customer.pk,
            business_unit_id=business_unit.pk,
            defaults={
                "assigned_salesperson_id": customer.assigned_salesperson_id,
                "status": customer.status,
                "created_by_id": customer.created_by_id,
                "updated_by_id": customer.updated_by_id,
            },
        )


def remove_default_customer_relationships(apps, schema_editor):
    BusinessUnit = apps.get_model("backoffice", "BusinessUnit")
    CustomerBusinessRelationship = apps.get_model("customers", "CustomerBusinessRelationship")
    try:
        business_unit = BusinessUnit.objects.get(code="SMART_CONTROL")
    except BusinessUnit.DoesNotExist:
        return
    CustomerBusinessRelationship.objects.filter(business_unit_id=business_unit.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_businessunit_businessunitmembership'),
        ('customers', '0001_initial'),
        ('salespeople', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBusinessRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo'), ('PROSPECT', 'Prospect')], default='PROSPECT', max_length=20)),
                ('commercial_since', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_relationships', to='salespeople.salesperson')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_relationships', to='backoffice.businessunit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_business_relationships_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_relationships', to='customers.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_business_relationships_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'relacionamento comercial do cliente',
                'verbose_name_plural': 'relacionamentos comerciais dos clientes',
                'ordering': ['customer__legal_name', 'business_unit__name'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'business_unit'), name='unique_customer_business_relationship')],
            },
        ),
        migrations.RunPython(create_default_customer_relationships, remove_default_customer_relationships),
    ]
