# Generated by Django 6.0.7 on 2026-08-13 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerbusinessrelationship'),
        ('salespeople', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAssignmentTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('transferred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('new_salesperson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_transfers_to', to='salespeople.salesperson')),
                ('previous_salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_transfers_from', to='salespeople.salesperson')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_transfers', to='customers.customerbusinessrelationship')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_assignment_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transferência de responsável comercial',
                'verbose_name_plural': 'transferências de responsáveis comerciais',
                'ordering': ['-transferred_at', '-id'],
                'permissions': [('transfer_customerassignment', 'Pode transferir responsável comercial')],
            },
        ),
    ]
