# Generated by Django 6.0.7 on 2026-08-12 16:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Login realizado'), ('LOGIN_FAILED', 'Falha de login'), ('LOGOUT', 'Logout'), ('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('ACTIVATE', 'Ativação'), ('DEACTIVATE', 'Desativação'), ('PUBLISH', 'Publicação'), ('UNPUBLISH', 'Despublicação'), ('PERMISSION_CHANGED', 'Permissão alterada'), ('ROLE_CHANGED', 'Papel alterado')], db_index=True, max_length=40)),
                ('module', models.CharField(db_index=True, max_length=80)),
                ('object_type', models.CharField(blank=True, max_length=120)),
                ('object_id', models.CharField(blank=True, max_length=120)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backoffice_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-timestamp', '-id'],
            },
        ),
    ]
