# Generated by Django 6.0.7 on 2026-08-13 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_business_unit(apps, schema_editor):
    BusinessUnit = apps.get_model("backoffice", "BusinessUnit")
    BusinessUnit.objects.get_or_create(
        code="SMART_CONTROL",
        defaults={
            "name": "Smart Control Brasil",
            "slug": "smart-control",
            "is_active": True,
        },
    )


def remove_default_business_unit(apps, schema_editor):
    BusinessUnit = apps.get_model("backoffice", "BusinessUnit")
    BusinessUnit.objects.filter(code="SMART_CONTROL", customer_relationships__isnull=True, memberships__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'unidade de negócio',
                'verbose_name_plural': 'unidades de negócio',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessUnitMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('ALL', 'Todos'), ('DEPARTMENT', 'Departamento'), ('TEAM', 'Equipe'), ('OWN', 'Próprios'), ('NONE', 'Nenhum')], default='OWN', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='backoffice.businessunit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_unit_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membership de unidade de negócio',
                'verbose_name_plural': 'memberships de unidades de negócio',
                'ordering': ['business_unit__name', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('user', 'business_unit'), name='unique_business_unit_membership')],
            },
        ),
        migrations.RunPython(create_default_business_unit, remove_default_business_unit),
    ]
