# Generated by Django 6.0.7 on 2026-08-28 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0002_alter_brand_logo_alter_productimage_image'),
        ('customers', '0003_customerassignmenttransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'segmento de mercado',
                'verbose_name_plural': 'segmentos de mercado',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProspectingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('location_description', models.CharField(max_length=180)),
                ('objective', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('ACTIVE', 'Ativa'), ('PAUSED', 'Pausada'), ('COMPLETED', 'Concluída'), ('ARCHIVED', 'Arquivada')], db_index=True, default='DRAFT', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_intelligence_campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('market_segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prospecting_campaigns', to='sales_intelligence.marketsegment')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prospecting_campaigns', to='commerce.product')),
            ],
            options={
                'verbose_name': 'campanha de prospecção',
                'verbose_name_plural': 'campanhas de prospecção',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(max_length=180)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('source', models.CharField(choices=[('GOOGLE_MAPS', 'Google Maps'), ('GOOGLE_SEARCH', 'Google Search'), ('MANUAL', 'Manual'), ('IMPORT', 'Importação'), ('OTHER', 'Outro')], db_index=True, default='GOOGLE_MAPS', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('RUNNING', 'Em execução'), ('COMPLETED', 'Concluída'), ('FAILED', 'Falhou'), ('CANCELLED', 'Cancelada')], db_index=True, default='PENDING', max_length=20)),
                ('requested_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('total_found', models.PositiveIntegerField(default=0)),
                ('total_new', models.PositiveIntegerField(default=0)),
                ('total_existing', models.PositiveIntegerField(default=0)),
                ('total_rejected', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='search_runs', to='sales_intelligence.prospectingcampaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_intelligence_search_runs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'execução de pesquisa',
                'verbose_name_plural': 'execuções de pesquisa',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('source_url', models.URLField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=180)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('processing_status', models.CharField(choices=[('DISCOVERED', 'Descoberto'), ('LINKED', 'Vinculado'), ('CREATED', 'Cliente criado'), ('DUPLICATE', 'Duplicado'), ('REJECTED', 'Rejeitado'), ('ERROR', 'Erro')], db_index=True, default='DISCOVERED', max_length=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_intelligence_search_results', to='customers.customer')),
                ('search_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='sales_intelligence.searchrun')),
            ],
            options={
                'verbose_name': 'resultado de pesquisa',
                'verbose_name_plural': 'resultados de pesquisa',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='searchrun',
            constraint=models.CheckConstraint(condition=models.Q(('requested_limit__isnull', True), ('requested_limit__gt', 0), _connector='OR'), name='sales_intelligence_searchrun_requested_limit_positive'),
        ),
        migrations.AddConstraint(
            model_name='searchrun',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('started_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='sales_intelligence_searchrun_finished_after_started'),
        ),
        migrations.AddConstraint(
            model_name='searchresult',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('search_run', 'external_id'), name='unique_search_result_external_id_per_run'),
        ),
        migrations.AddConstraint(
            model_name='searchresult',
            constraint=models.CheckConstraint(condition=models.Q(('processing_status__in', ['DISCOVERED', 'DUPLICATE', 'REJECTED', 'ERROR']), ('customer__isnull', False), _connector='OR'), name='sales_intelligence_processed_result_requires_customer'),
        ),
    ]
