# Generated by Django 6.0.7 on 2026-08-28 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customerassignmenttransfer'),
        ('sales_intelligence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='name_phone_key',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='source_url_key',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='searchrun',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['search_run', 'processing_status'], name='si_result_run_status_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['customer'], name='si_result_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='searchrun',
            index=models.Index(fields=['campaign', 'status', 'created_at'], name='si_run_campaign_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='searchresult',
            constraint=models.UniqueConstraint(condition=models.Q(('source_url_key', ''), _negated=True), fields=('search_run', 'source_url_key'), name='unique_search_result_source_url_per_run'),
        ),
        migrations.AddConstraint(
            model_name='searchresult',
            constraint=models.UniqueConstraint(condition=models.Q(('name_phone_key', ''), _negated=True), fields=('search_run', 'name_phone_key'), name='unique_search_result_name_phone_per_run'),
        ),
    ]
