# Generated by Django 6.0.7 on 2026-08-28 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customerassignmenttransfer'),
        ('sales_intelligence', '0002_searchresult_name_phone_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignProspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('REVIEWED', 'Revisado'), ('CONTACT_READY', 'Pronto para contato'), ('DISCARDED', 'Descartado')], db_index=True, default='NEW', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to='sales_intelligence.prospectingcampaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_intelligence_campaign_prospects_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_intelligence_campaign_prospects', to='customers.customer')),
                ('origin_search_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_prospect_origins', to='sales_intelligence.searchresult')),
            ],
            options={
                'verbose_name': 'prospect de campanha',
                'verbose_name_plural': 'prospects de campanha',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='si_cp_campaign_status_idx'), models.Index(fields=['customer'], name='si_prospect_customer_idx')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'customer'), name='unique_campaign_prospect_customer')],
            },
        ),
    ]
